spring.application.name=WalletSpringboot
server.port=8008
server.address=localhost
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=springdb
spring.datasource.password=icsd
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
file.upload.dir=D:/docfolder
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:D:/docfolder/,classpath:/static/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmail@gmail.com
spring.mail.password=yourapppasswordofsixteencharacters
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.plan.basic.expiry-days=15
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
welcome.email.delay.minutes=30